apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ClusterCurator
metadata:
  name: my-cluster
  namespace: my-cluster
  labels:
    open-cluster-management: curator
spec:
  desiredCuration: install
  install:
    prehook:
    - name: Demo Job Template
      extra_vars:
        sn_severity: 1
        sn_priority: 1
        appName: prehook job
        target_clusters:
          - my-cluster
    - name: Demo Job Template
    posthook:
    - name: Demo Job Template
      extra_vars:
        sn_severity: 2
        sn_priority: 2
        appName: posthook job
        target_clusters:
          - my-cluster
