apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cluster-curator-controller
  name: cluster-curator-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cluster-curator-controller
  template:
    metadata:
      labels:
        name: cluster-curator-controller
    spec:
      imagePullSecrets:
        - name: multiclusterhub-operator-pull-secret
      containers:
      - command:
        - ./cluster-curator-controller
        - "-v"
        - "2"
        image: quay.io/open-cluster-management/cluster-curator-controller@sha256:f7210661a8aa97d0bd94af08a3b5b0ff3cf97c9f6775a2495e9a9c0a2d2084cf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        imagePullPolicy: Always
        name: cluster-curator-controller
        resources:
          limits:
            cpu: "10m"
            memory: "45Mi"
          requests:
            cpu: "3m"                     # Runs < 2m most of the time
            memory: "25Mi"                # Runs between 25-28Mi
      serviceAccountName: cluster-curator
