apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cluster-curator-controller
  name: cluster-curator-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cluster-curator-controller
  template:
    metadata:
      labels:
        name: cluster-curator-controller
    spec:
      containers:
      - command:
        - ./cluster-curator-controller
        - "-v"
        - "2"
        image: registry.ci.openshift.org/open-cluster-management/2.3:cluster-curator-controller
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: IMAGE_URI
          value: registry.ci.openshift.org/open-cluster-management/2.3:cluster-curator-controller
        imagePullPolicy: Always
        name: cluster-curator-controller
        resources:
          limits:
            cpu: "10m"
            memory: "45Mi"
          requests:
            cpu: "3m"                     # Runs < 2m most of the time
            memory: "25Mi"                # Runs between 25-28Mi
      serviceAccountName: cluster-curator
